name: Build

on:
  workflow_call:
    inputs:
      java-version:
        type: string
        default: '17'
    secrets:
      GH_TOKEN_REPO:
        required: true

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: ${{ inputs.java-version }}
          cache: maven

      - run: ./mvnw -U test -Dgithub_token=${{ secrets.GH_TOKEN_REPO }} -DfailIfNoTests

      - uses: codecov/codecov-action@v4
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
